"""Where the chain's values come from (T40): the manifest, the server, a local values file.

The manifest keeps what belongs to the chain; a value of one installation is a marker the run
fills in — ``@server`` from what the server says, ``@dialect`` from the manifest's dialect table
of the write data source's product — and the per-profile values file beside the profiles
overrides any of them. A value nobody filled in makes the steps that name it skip, saying which
line to add where; a text with a placeholder in it is never sent.
"""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from denodo_cli.commands.verify import ChainError, load_chain, load_values_file

MANIFEST = """
[values]
database = "denodo_skills_test"
fixture_base = "https://example.org/data"
write_dialect = "@server"
write_identity = "@dialect"

[dialects.sqlserver]
write_identity = "INT IDENTITY(1001,1)"

[dialects.postgresql]
write_identity = "INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001)"
write_timestamp = "TIMESTAMP(0)"

[not_run]
"skills/catalog/SKILL.md#Database[1]" = "grammar, not a statement"

[[step]]
id = "database"
kind = "fixture"
channel = "vql"
vql = "SELECT 1;"
"""


class ManifestSectionsTest(unittest.TestCase):
    def setUp(self):
        self.path = Path(tempfile.mkdtemp()) / "chain.toml"

    def load(self, text):
        self.path.write_text(text, encoding="utf-8")
        return load_chain(self.path)

    def test_dialect_tables_and_not_run_are_read(self):
        chain = self.load(MANIFEST)
        self.assertEqual(chain.dialects["sqlserver"], {"write_identity": "INT IDENTITY(1001,1)"})
        self.assertEqual(chain.dialects["postgresql"]["write_timestamp"], "TIMESTAMP(0)")
        self.assertEqual(chain.not_run, {"skills/catalog/SKILL.md#Database[1]": "grammar, not a statement"})

    def test_a_manifest_without_them_has_empty_ones(self):
        chain = self.load('[[step]]\nid = "a"\nkind = "fixture"\nchannel = "vql"\nvql = "SELECT 1;"\n')
        self.assertEqual(chain.dialects, {})
        self.assertEqual(chain.not_run, {})

    def test_a_not_run_entry_needs_a_reason(self):
        with self.assertRaisesRegex(ChainError, "not_run"):
            self.load(MANIFEST.replace('= "grammar, not a statement"', "= 3"))

    def test_a_dialect_must_be_a_table_of_strings(self):
        with self.assertRaisesRegex(ChainError, "dialects"):
            self.load(MANIFEST.replace('write_identity = "INT IDENTITY(1001,1)"', "write_identity = [1]"))

    def test_known_keys_are_the_values_and_every_dialect_key(self):
        chain = self.load(MANIFEST)
        self.assertEqual(chain.known_values(),
                         {"database", "fixture_base", "write_dialect", "write_identity", "write_timestamp"})


class ValuesFileTest(unittest.TestCase):
    KNOWN = {"database", "fixture_base", "write_identity"}

    def setUp(self):
        self.path = Path(tempfile.mkdtemp()) / "verify.toml"

    def test_a_missing_file_gives_nothing(self):
        self.assertEqual(load_values_file(self.path, "lab", self.KNOWN), {})

    def test_only_the_profile_s_own_table_is_read(self):
        self.path.write_text('[dev]\nfixture_base = "/a"\n[lab]\nfixture_base = "/b"\n', encoding="utf-8")
        self.assertEqual(load_values_file(self.path, "lab", self.KNOWN), {"fixture_base": "/b"})
        self.assertEqual(load_values_file(self.path, "prod", self.KNOWN), {})

    def test_an_unknown_key_names_the_file_the_table_and_the_known_keys(self):
        self.path.write_text('[lab]\nfixture_bas = "/b"\n', encoding="utf-8")
        with self.assertRaises(ChainError) as caught:
            load_values_file(self.path, "lab", self.KNOWN)
        message = str(caught.exception)
        self.assertIn(str(self.path), message)
        self.assertIn("[lab]", message)
        self.assertIn("fixture_bas", message)
        self.assertIn("fixture_base", message)

    def test_numbers_are_read_as_text(self):
        self.path.write_text('[lab]\nfixture_base = 7\n', encoding="utf-8")
        self.assertEqual(load_values_file(self.path, "lab", self.KNOWN), {"fixture_base": "7"})

    def test_a_table_inside_the_profile_table_is_refused(self):
        self.path.write_text('[lab.fixture_base]\nx = 1\n', encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "fixture_base"):
            load_values_file(self.path, "lab", self.KNOWN)

    def test_a_file_that_is_not_toml_is_refused(self):
        self.path.write_text('[lab\n', encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "verify.toml"):
            load_values_file(self.path, "lab", self.KNOWN)

    def test_a_profile_entry_that_is_not_a_table_is_refused(self):
        self.path.write_text('lab = "x"\n', encoding="utf-8")
        with self.assertRaisesRegex(ChainError, r"\[lab\]"):
            load_values_file(self.path, "lab", self.KNOWN)


if __name__ == "__main__":
    unittest.main()
