"""Where the chain's values come from (T40): the manifest, the server, a local values file.

The manifest keeps what belongs to the chain; a value of one installation is a marker the run
fills in — ``@server`` from what the server says, ``@dialect`` from the manifest's dialect table
of the write data source's product — and the per-profile values file beside the profiles
overrides any of them. A value nobody filled in makes the steps that name it skip, saying which
line to add where; a text with a placeholder in it is never sent.
"""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from denodo_cli.commands.verify import ChainError, load_chain, load_values_file, run_chain
from denodo_cli.profiles import Profile
from denodo_cli.transports.base import HttpResult, VqlResult

MANIFEST = """
[values]
database = "denodo_skills_test"
fixture_base = "https://example.org/data"
write_dialect = "@server"
write_identity = "@dialect"

[dialects.sqlserver]
write_identity = "INT IDENTITY(1001,1)"

[dialects.postgresql]
write_identity = "INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001)"
write_timestamp = "TIMESTAMP(0)"

[not_run]
"skills/catalog/SKILL.md#Database[1]" = "grammar, not a statement"

[[step]]
id = "database"
kind = "fixture"
channel = "vql"
vql = "SELECT 1;"
"""


class ManifestSectionsTest(unittest.TestCase):
    def setUp(self):
        self.path = Path(tempfile.mkdtemp()) / "chain.toml"

    def load(self, text):
        self.path.write_text(text, encoding="utf-8")
        return load_chain(self.path)

    def test_dialect_tables_and_not_run_are_read(self):
        chain = self.load(MANIFEST)
        self.assertEqual(chain.dialects["sqlserver"], {"write_identity": "INT IDENTITY(1001,1)"})
        self.assertEqual(chain.dialects["postgresql"]["write_timestamp"], "TIMESTAMP(0)")
        self.assertEqual(chain.not_run, {"skills/catalog/SKILL.md#Database[1]": "grammar, not a statement"})

    def test_a_manifest_without_them_has_empty_ones(self):
        chain = self.load('[[step]]\nid = "a"\nkind = "fixture"\nchannel = "vql"\nvql = "SELECT 1;"\n')
        self.assertEqual(chain.dialects, {})
        self.assertEqual(chain.not_run, {})

    def test_a_not_run_entry_needs_a_reason(self):
        with self.assertRaisesRegex(ChainError, "not_run"):
            self.load(MANIFEST.replace('= "grammar, not a statement"', "= 3"))

    def test_a_dialect_must_be_a_table_of_strings(self):
        with self.assertRaisesRegex(ChainError, "dialects"):
            self.load(MANIFEST.replace('write_identity = "INT IDENTITY(1001,1)"', "write_identity = [1]"))

    def test_known_keys_are_the_values_and_every_dialect_key(self):
        chain = self.load(MANIFEST)
        self.assertEqual(chain.known_values(),
                         {"database", "fixture_base", "write_dialect", "write_identity", "write_timestamp"})


class ValuesFileTest(unittest.TestCase):
    KNOWN = {"database", "fixture_base", "write_identity"}

    def setUp(self):
        self.path = Path(tempfile.mkdtemp()) / "verify.toml"

    def test_a_missing_file_gives_nothing(self):
        self.assertEqual(load_values_file(self.path, "lab", self.KNOWN), {})

    def test_only_the_profile_s_own_table_is_read(self):
        self.path.write_text('[dev]\nfixture_base = "/a"\n[lab]\nfixture_base = "/b"\n', encoding="utf-8")
        self.assertEqual(load_values_file(self.path, "lab", self.KNOWN), {"fixture_base": "/b"})
        self.assertEqual(load_values_file(self.path, "prod", self.KNOWN), {})

    def test_an_unknown_key_names_the_file_the_table_and_the_known_keys(self):
        self.path.write_text('[lab]\nfixture_bas = "/b"\n', encoding="utf-8")
        with self.assertRaises(ChainError) as caught:
            load_values_file(self.path, "lab", self.KNOWN)
        message = str(caught.exception)
        self.assertIn(str(self.path), message)
        self.assertIn("[lab]", message)
        self.assertIn("fixture_bas", message)
        self.assertIn("fixture_base", message)

    def test_numbers_are_read_as_text(self):
        self.path.write_text('[lab]\nfixture_base = 7\n', encoding="utf-8")
        self.assertEqual(load_values_file(self.path, "lab", self.KNOWN), {"fixture_base": "7"})

    def test_a_table_inside_the_profile_table_is_refused(self):
        self.path.write_text('[lab.fixture_base]\nx = 1\n', encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "fixture_base"):
            load_values_file(self.path, "lab", self.KNOWN)

    def test_a_file_that_is_not_toml_is_refused(self):
        self.path.write_text('[lab\n', encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "verify.toml"):
            load_values_file(self.path, "lab", self.KNOWN)

    def test_a_profile_entry_that_is_not_a_table_is_refused(self):
        self.path.write_text('lab = "x"\n', encoding="utf-8")
        with self.assertRaisesRegex(ChainError, r"\[lab\]"):
            load_values_file(self.path, "lab", self.KNOWN)


def profile(**over):
    base = dict(name="lab", host="h", port=9996, database="admin", user="admin", password="p",
                production=False, transport="vql_psycopg2", marketplace_url=None, marketplace_server_id=None)
    base.update(over)
    return Profile(**base)


class Server:
    """A fake Virtual DataPort that answers the feature probe the way 9.5.1 does.

    ``settings`` is what ``GET_PARAMETER`` reads (``None`` = refused, a non-administrator);
    ``adapter``/``catalog`` the cache database; every other statement is accepted and recorded.
    """
    sent: list[str] = []
    settings: dict | None = {"llm_enabled": "true", "llm_model": "gpt-5.1",
                             "embedding_model": "text-embedding-3-large"}
    adapter, catalog, plus, impersonation = "sqlserver", "enterprise_data", True, True

    def __init__(self, profile, database=None):
        self.database = database

    def execute(self, statement):
        Server.sent.append(statement)
        if "VALIDATE_MPP_LICENSE" in statement:
            return VqlResult(statement, ["max_processors", "current_processors", "status", "details"],
                             [[2147483647 if Server.plus else -1, -1, -5, "x"]])
        if "GET_CACHE_CONFIGURATION" in statement:
            return VqlResult(statement, ["database_datasource_name", "datasource_name", "adapter_database_name",
                                         "adapter_database_version", "status", "target_catalog", "target_schema"],
                             [["admin", "vdpcachedatasource", Server.adapter, "1", "ON", Server.catalog, "dbo"]])
        if "GET_PARAMETER" in statement:
            if Server.settings is None:
                raise RuntimeError("Error executing query.")
            names = [part.split("'")[0] for part in statement.split("SELECT '")[1:]]
            return VqlResult(statement, ["name", "property_value"], [[n, Server.settings.get(n)] for n in names])
        if statement.startswith("DESC USER"):
            return VqlResult(statement, ["name", "adminglobal"], [["admin", "true"]])
        if "impersonate_user" in statement and "probe" in statement:
            if not Server.impersonation:
                raise RuntimeError("This user cannot impersonate.")
            return VqlResult(statement, ["probe"], [[1]])
        if statement.upper().startswith("SELECT"):
            return VqlResult(statement, ["c"], [["x"]])
        return VqlResult(statement, None, None)

    def close(self):
        pass


def reset_server(**over):
    Server.sent = []
    Server.settings = {"llm_enabled": "true", "llm_model": "gpt-5.1", "embedding_model": "text-embedding-3-large"}
    Server.adapter, Server.catalog, Server.plus, Server.impersonation = "sqlserver", "enterprise_data", True, True
    for key, value in over.items():
        setattr(Server, key, value)


RUN = """
[values]
database = "denodo_skills_test"
embedding_model = "@server"
write_catalog = "@server"
write_dialect = "@server"
write_identity = "@dialect"

[dialects.sqlserver]
write_identity = "INT IDENTITY(1001,1)"

[dialects.postgresql]
write_identity = "INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001)"

[not_run]
"skills/x/SKILL.md#A" = "grammar"
"skills/x/SKILL.md#B" = "fragment"

[cleanup]
writes = ["SELECT 'drop' FROM t WHERE c = '{write_catalog}'"]
vql = ["DROP DATABASE IF EXISTS {database} CASCADE"]

[[step]]
id = "embed"
kind = "fixture"
channel = "vql"
vql = "SELECT EMBED_AI('x', '{embedding_model}');"

[[step]]
id = "table"
kind = "fixture"
channel = "vql"
writes = true
vql = "CREATE REMOTE TABLE t CATALOG = '{write_catalog}' (id {write_identity});"

[[step]]
id = "after"
kind = "fixture"
channel = "vql"
vql = "SELECT 'after';"
"""


class ResolveTest(unittest.TestCase):
    def setUp(self):
        reset_server()
        self.dir = Path(tempfile.mkdtemp())
        self.path = self.dir / "chain.toml"

    def chain(self, text=RUN):
        self.path.write_text(text, encoding="utf-8")
        return load_chain(self.path)

    def run_it(self, chain=None, **kw):
        kw.setdefault("with_writes", True)
        return run_chain(profile(), chain or self.chain(), root=self.dir, vql_factory=Server, **kw)

    def test_a_manifest_without_markers_or_requirements_asks_the_server_nothing(self):
        chain = self.chain('[values]\ndatabase = "d"\n[[step]]\nid = "a"\nkind = "fixture"\n'
                           'channel = "vql"\nvql = "SELECT 1;"\n')
        doc, code = self.run_it(chain)
        self.assertEqual(code, 0)
        self.assertFalse(any("VALIDATE_MPP_LICENSE" in s or "GET_PARAMETER" in s for s in Server.sent))
        self.assertNotIn("features", doc)

    def test_server_values_and_where_each_came_from(self):
        doc, code = self.run_it()
        self.assertEqual(code, 0, doc)
        self.assertIn("SELECT EMBED_AI('x', 'text-embedding-3-large')", Server.sent)
        self.assertIn("CREATE REMOTE TABLE t CATALOG = 'enterprise_data' (id INT IDENTITY(1001,1))", Server.sent)
        self.assertEqual(doc["values_from"]["embedding_model"], "server")
        self.assertEqual(doc["values_from"]["write_identity"], "dialect")
        self.assertEqual(doc["values_from"]["database"], "manifest")
        self.assertEqual(doc["features"]["cache"]["adapter"], "sqlserver")
        self.assertEqual(doc["summary"]["not_run"], 2)

    def test_the_dialect_follows_the_product(self):
        reset_server(adapter="postgresql")
        self.run_it()
        self.assertIn("CREATE REMOTE TABLE t CATALOG = 'enterprise_data' "
                      "(id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001))", Server.sent)

    def test_the_values_file_beats_the_server_and_the_flag_beats_the_file(self):
        doc, _ = self.run_it(file_values={"embedding_model": "my-model", "database": "from_file"},
                             values_file=self.dir / "verify.toml", database="from_flag")
        self.assertIn("SELECT EMBED_AI('x', 'my-model')", Server.sent)
        self.assertEqual(doc["values_from"]["embedding_model"], "file")
        self.assertEqual(doc["values"]["database"], "from_flag")
        self.assertEqual(doc["values_file"], str(self.dir / "verify.toml"))

    def test_an_unknown_product_leaves_the_dialect_value_unresolved_and_skips_its_step(self):
        reset_server(adapter="oracle")
        doc, code = self.run_it(values_file=self.dir / "verify.toml")
        self.assertEqual(code, 0, doc)
        table = next(s for s in doc["steps"] if s["id"] == "table")
        self.assertTrue(table["skipped"])
        self.assertIn("write_identity", table["reason"])
        self.assertIn("oracle", table["reason"])
        self.assertIn(str(self.dir / "verify.toml"), table["reason"])
        self.assertFalse(next(s for s in doc["steps"] if s["id"] == "after")["skipped"])
        self.assertFalse(any("{write_identity}" in s for s in Server.sent))
        self.assertEqual(doc["values_from"]["write_identity"], "unresolved")

    def test_a_non_administrator_leaves_server_settings_unresolved(self):
        reset_server(settings=None)
        doc, code = self.run_it()
        self.assertEqual(code, 0, doc)
        embed = next(s for s in doc["steps"] if s["id"] == "embed")
        self.assertTrue(embed["skipped"])
        self.assertIn("embedding_model", embed["reason"])
        self.assertIsNone(doc["features"]["llm"])

    def test_a_cleanup_statement_naming_an_unresolved_value_is_reported_not_sent(self):
        reset_server(catalog=None)
        doc, code = self.run_it()
        self.assertEqual(code, 0, doc)
        self.assertFalse(any("{write_catalog}" in s for s in Server.sent))
        skipped = [s for s in doc["cleanup"]["statements"] if s.get("skipped")]
        self.assertEqual(len(skipped), 1)
        self.assertIn("write_catalog", skipped[0]["reason"])
        self.assertIn("DROP DATABASE IF EXISTS denodo_skills_test CASCADE", Server.sent)


REQUIRES = """
[values]
database = "d"

[[step]]
id = "tags"
kind = "fixture"
channel = "vql"
requires = ["enterprise_plus"]
vql = "CREATE TAG verify_pii;"

[[step]]
id = "as-someone"
kind = "fixture"
channel = "vql"
requires = ["impersonation", "cache"]
vql = "SELECT 'as someone';"
"""


class RequiresTest(unittest.TestCase):
    def setUp(self):
        reset_server()
        self.dir = Path(tempfile.mkdtemp())
        self.path = self.dir / "chain.toml"
        self.path.write_text(REQUIRES, encoding="utf-8")

    def test_a_step_runs_when_the_server_has_what_it_requires(self):
        doc, code = run_chain(profile(), load_chain(self.path), root=self.dir, vql_factory=Server)
        self.assertEqual(code, 0, doc)
        self.assertEqual([s["skipped"] for s in doc["steps"]], [False, False])

    def test_a_missing_feature_skips_the_step_saying_why(self):
        reset_server(plus=False, impersonation=False)
        doc, code = run_chain(profile(), load_chain(self.path), root=self.dir, vql_factory=Server)
        self.assertEqual(code, 0, doc)
        tags, someone = doc["steps"]
        self.assertTrue(tags["skipped"])
        self.assertIn("enterprise_plus", tags["reason"])
        self.assertIn("Enterprise Plus", tags["reason"])
        self.assertIn("impersonat", someone["reason"])
        self.assertNotIn("CREATE TAG verify_pii", Server.sent)

    def test_an_unknown_feature_runs_the_step(self):
        class Silent(Server):
            def execute(self, statement):
                if "VALIDATE_MPP_LICENSE" in statement or "GET_CACHE_CONFIGURATION" in statement:
                    raise RuntimeError("no")
                return super().execute(statement)

        doc, code = run_chain(profile(), load_chain(self.path), root=self.dir, vql_factory=Silent)
        self.assertEqual([s["skipped"] for s in doc["steps"]], [False, False])
        self.assertIsNone(doc["features"]["enterprise_plus"])

    def test_an_unknown_requirement_is_a_manifest_error(self):
        self.path.write_text(REQUIRES.replace('"cache"]', '"caches"]'), encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "caches"):
            load_chain(self.path)


NEEDS = """
[values]
database = "d"
embedding_model = "@server"

[[step]]
id = "vectors"
kind = "fixture"
channel = "vql"
vql = "CREATE VIEW v AS SELECT EMBED_AI('x', '{embedding_model}') AS e FROM Dual();"

[[step]]
id = "search"
kind = "fixture"
channel = "vql"
needs = ["vectors"]
vql = "SELECT * FROM v;"

[[step]]
id = "search-again"
kind = "fixture"
channel = "vql"
needs = ["search"]
vql = "SELECT * FROM v WHERE 1 = 1;"

[[step]]
id = "unrelated"
kind = "fixture"
channel = "vql"
vql = "SELECT 'unrelated';"
"""

CAPTURE = """
[values]
database = "d"

[[step]]
id = "make-job"
kind = "template"
channel = "http"
scheduler = true
address = "skills/marketplace/SKILL.md#Tag, with an assignment"
capture = { job_id = "id" }

[[step]]
id = "use-job"
kind = "fixture"
channel = "vql"
vql = "SELECT '{job_id}';"
"""


class SkipsTravelTest(unittest.TestCase):
    """A skip must not turn into a failure further down (T40 review): a step that needs a
    skipped step is skipped with its reason, transitively, and a value a skipped step would
    have captured is unresolved for every later step that names it."""

    def setUp(self):
        reset_server()
        self.dir = Path(tempfile.mkdtemp())
        self.path = self.dir / "chain.toml"

    def run_text(self, text, **kw):
        self.path.write_text(text, encoding="utf-8")
        return run_chain(profile(), load_chain(self.path), root=self.dir, vql_factory=Server, **kw)

    def test_a_skip_takes_the_steps_that_need_it_transitively(self):
        reset_server(settings=None)              # a non-administrator: the model stays unresolved
        doc, code = self.run_text(NEEDS)
        self.assertEqual(code, 0, doc)
        steps = {s["id"]: s for s in doc["steps"]}
        self.assertEqual(steps["vectors"]["cause"], "value")
        self.assertEqual(steps["search"]["cause"], "needs")
        self.assertIn("'vectors'", steps["search"]["reason"])
        self.assertEqual(steps["search-again"]["cause"], "needs")
        self.assertFalse(steps["unrelated"]["skipped"])
        self.assertNotIn("SELECT * FROM v;", Server.sent)
        self.assertEqual(doc["summary"]["skipped_because"], {"value": 1, "needs": 2})

    def test_needs_must_name_an_earlier_step(self):
        self.path.write_text(NEEDS.replace('needs = ["vectors"]', 'needs = ["search-again"]'), encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "not an earlier step"):
            load_chain(self.path)

    def test_what_a_skipped_step_would_capture_is_never_sent_as_a_placeholder(self):
        root = self.dir
        (root / "skills" / "marketplace").mkdir(parents=True)
        (root / "skills" / "marketplace" / "SKILL.md").write_text(
            "## Tag, with an assignment\n\n```bash\n# verified: 9.5.1 (live, 2026-09-10)\n"
            "api post /public/api/tags --json '{\"name\":\"x\"}'\n```\n", encoding="utf-8")
        doc, code = self.run_text(CAPTURE)           # no --with-scheduler: make-job is skipped
        self.assertEqual(code, 0, doc)
        use = doc["steps"][1]
        self.assertTrue(use["skipped"])
        self.assertIn("make-job", use["reason"])
        self.assertFalse(any("{job_id}" in s for s in Server.sent))
        self.assertNotIn("job_id", doc["unresolved"])     # not a value the installation gives

    def test_without_treats_the_server_as_lacking_a_feature(self):
        self.path.write_text(REQUIRES, encoding="utf-8")
        doc, code = run_chain(profile(), load_chain(self.path), root=self.dir, vql_factory=Server,
                              assume_missing=("enterprise_plus",))
        self.assertEqual(code, 0, doc)
        self.assertEqual([s.get("cause") for s in doc["steps"]], ["server", None])
        self.assertEqual(doc["assumed_missing"], ["enterprise_plus"])
        self.assertIn("--without enterprise_plus", doc["steps"][0]["reason"])

    def test_a_value_named_in_the_skill_block_itself_counts(self):
        (self.dir / "skills" / "x").mkdir(parents=True)
        (self.dir / "skills" / "x" / "SKILL.md").write_text(
            "## Search\n\n```sql\n-- verified: 9.5.1 (live, 2026-10-02)\n"
            "SELECT EMBED_AI('x', '{embedding_model}') FROM Dual();\n```\n", encoding="utf-8")
        reset_server(settings=None)
        doc, code = self.run_text('[values]\ndatabase = "d"\nembedding_model = "@server"\n'
                                  '[[step]]\nid = "s"\nkind = "template"\nchannel = "vql"\n'
                                  'address = "skills/x/SKILL.md#Search"\n')
        self.assertEqual(doc["steps"][0]["cause"], "value")

    def test_the_reason_names_the_default_values_file_when_there_is_none_yet(self):
        import os
        from unittest import mock
        reset_server(settings=None)
        profiles = self.dir / "conf" / "profiles.toml"
        with mock.patch.dict(os.environ, {"DENODO_PROFILES": str(profiles)}):
            doc, _ = self.run_text(NEEDS)
        self.assertIn(str(self.dir / "conf" / "verify.toml"), doc["steps"][0]["reason"])


class SettableValuesTest(unittest.TestCase):
    MANIFEST = """
local_values = ["fixture_base"]

[values]
database = "denodo_skills_test"
tag_prefix = "verify_"
fixture_base = "https://example.org/data"
embedding_model = "@server"
write_dialect = "@server"
write_identity = "@dialect"
jdbc_password = "@encrypt-throwaway"

[dialects.sqlserver]
write_identity = "INT IDENTITY(1001,1)"

[[step]]
id = "a"
kind = "fixture"
channel = "vql"
vql = "SELECT 1;"
"""

    def setUp(self):
        self.path = Path(tempfile.mkdtemp()) / "chain.toml"
        self.path.write_text(self.MANIFEST, encoding="utf-8")
        self.chain = load_chain(self.path)

    def test_a_file_may_set_installation_values_only(self):
        self.assertEqual(self.chain.settable_values(),
                         {"fixture_base", "embedding_model", "write_dialect", "write_identity"})

    def test_the_chain_s_own_values_are_refused_saying_why(self):
        values = self.path.with_name("verify.toml")
        own = self.chain.known_values() - self.chain.settable_values()
        for key in ("database", "tag_prefix", "jdbc_password"):
            values.write_text(f'[lab]\n{key} = "x"\n', encoding="utf-8")
            with self.subTest(key=key), self.assertRaisesRegex(ChainError, "value of the chain itself"):
                load_values_file(values, "lab", self.chain.settable_values(), own=own)

    def test_local_values_inside_values_is_refused(self):
        self.path.write_text(self.MANIFEST.replace('local_values = ["fixture_base"]\n', '').replace(
            '[values]\n', '[values]\nlocal_values = ["fixture_base"]\n'), encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "top of the manifest"):
            load_chain(self.path)

    def test_local_values_must_be_values(self):
        self.path.write_text(self.MANIFEST.replace('local_values = ["fixture_base"]', 'local_values = ["nope"]'),
                             encoding="utf-8")
        with self.assertRaisesRegex(ChainError, "local_values"):
            load_chain(self.path)

    def test_a_product_name_matches_its_dialect_table_in_any_case(self):
        from denodo_cli.commands.verify import resolve_values
        values, origin, _ = resolve_values(self.chain, database=None, file_values=None,
                                           server={"write_dialect": "SQLServer"}, values_file=None,
                                           profile_name="lab")
        self.assertEqual(values["write_identity"], "INT IDENTITY(1001,1)")


if __name__ == "__main__":
    unittest.main()
